### ISSUE TITLE
Instruções repetidas

### ISSUE THREAD

**Issue by orlandosaraivajr** [Wess11/Prova2#1]
Validação 
$nome = (!isset($_POST['nome'])) ? '' : $_POST['nome'];
repetida em vários trechos. Caberia uma função valida_entrada ou mesmo um método ? Faz sentido ?

https://github.com/Wess11/Prova2/blob/d0ee21d3a830ad5266973827b6c6d9d0a6dfeeb0/Prova2/cadastra.php#L8

**Comment by Wess11** [comment]
Obrigado pelo feedback professor, faz sentido sim!
